package ar.edu.unlam.pb2.dominio;

public enum MenuInstitucion {
	AGREGAR_NIVEL, ELIMINAR_NIVEL, AGREGAR_ALUMNO, ELIMINAR_ALUMNO, OBTENER_ALUMNOS_ORDENADOS_POR_EDAD , DISTRIBUIR_ALUMNOS_A_NIVELES, AGREGAR_DOCENTE, ELIMINAR_DOCENTE , SALIR
}
